### ISSUE TITLE
can't appear to change API endpoint under some versions of Firefox and Chrome

### ISSUE THREAD

**Issue by heckj** [RackHD/on-web-ui#51]
From Slack (http://codecommunity.slack.com/) channel:

johnhogenmiller
> Can't change the Monorail endpoint url in Firefox?
> Firefox 43.0.4.  You can't erase the default http://localhost... value. ALl you can do is insert characters at the beginning of the string.

rlarkin
> I found that sometimes I can and can't change it in both firefox and chrome.

johnhogenmiller
> If I use the brower's inspect element, I can modify the value and then apply

rlarkin
> `sed -i -e "s/http:\/\/localhost:9090\/api\/1.1\//http:\/\/$default_ip:8080\/api\/1.1\//" /var/renasar/on-http/static/web-ui/bundle/monorail.js`
> define default_ip first

**Comment by rolandpoulter** [comment]
Safari has the same issue.

**Comment by rolandpoulter** [comment]
This is a problem with how the App Toolbar is constructed. The way content changes in the toolbar is a little goofy, honestly surprised it worked in Chrome.

I planning on redesigning the toolbar. So I'll also refactor how app interact with the toolbar in order to fix this issue.

Until then Firefox and Safari are broken. Please use Chrome.

**Comment by rolandpoulter** [comment]
If you need to use Safari or Firefox you can manually set the MonoRail API Endpoint.
Open developer console and type:
```
window.localStorage.setItem('MONORAIL_API', 'http://localhost:9090/api/1.1/');
```
Then refresh the page.

**Comment by rolandpoulter** [comment]
Found the problem!

Here https://github.com/RackHD/on-web-ui/pull/53/files#diff-4049002e8833f6c8b075f1ab66827736L56 it was setting `user-select` css field and for some reason it was interfering with Firefox and Safari but not Chrome.
