### ISSUE TITLE
Unexpected glyphs in the UI

### ISSUE THREAD

**Issue by emc-pattej2** [RackHD/on-web-ui#73]
When I load the UI from the live site, I see this:
RackHD » Management Console » Dashboard

When I host the same UI files from my own web server, I see this:
RackHDÂ Â»Â Management ConsoleÂ Â»Â Dashboard

I see this sort of thing in various parts of the UI
I'm using Chrome
The 'inspect' features reports 6 glyphs being rendered instead of 3 glyphs
I can't find anything else that is different between these two use cases

Does anyone know why this is happening?
Is there something on the live site that my web server is missing?

**Comment by rolandpoulter** [comment]
That is strange. Are you serving the UI from `on-http` from your own computer?
